// GENERATED CODE - DO NOT MODIFY BY HAND
// lib/models/downloaded_content.g.dart
//
// This is the Hive type adapter for DownloadedContent.
// Normally generated by `flutter pub run build_runner build`, but written
// manually here to avoid a build_runner dependency in the project.

part of 'downloaded_content.dart';

class DownloadedContentAdapter extends TypeAdapter<DownloadedContent> {
  @override
  final int typeId = 0;

  @override
  DownloadedContent read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return DownloadedContent(
      id: fields[0] as String,
      title: fields[1] as String,
      contentType: fields[2] as String,
      encryptedFilePath: fields[3] as String,
      downloadedAt: fields[4] as DateTime,
      fileSizeBytes: fields[5] as int,
      thumbnailUrl: fields[6] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, DownloadedContent obj) {
    writer
      ..writeByte(7)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.title)
      ..writeByte(2)
      ..write(obj.contentType)
      ..writeByte(3)
      ..write(obj.encryptedFilePath)
      ..writeByte(4)
      ..write(obj.downloadedAt)
      ..writeByte(5)
      ..write(obj.fileSizeBytes)
      ..writeByte(6)
      ..write(obj.thumbnailUrl);
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadedContentAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;

  @override
  int get hashCode => typeId.hashCode;
}
